# Site settings
title: arthr.me
description: >-
  Nada faz muito sentido.

baseurl: ""
url: "https://arthr.me"

lang: pt-BR
timezone: America/Sao_Paulo
encoding: utf-8

logo: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128

author:
  name: Arthur Freitas
  url: https://arthr.me
  email: email@arthr.me
  picture: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128


# Menu
main_menu:
  - index.md
  - agora.html
  - blog.html
  - sobre.md

# Build settings
include:
  - _pages
  - _redirects

permalink: /blog/:year/:month/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-relative-links

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layout: archive
  permalinks:
    year: "/blog/:year/"
    month: "/blog/:year/:month/"
    tag: "/blog/tags/:name/"
  slug_mode: latin

seo:
  name: Arthur Freitas
  links:
    - https://github.com/arthrfrts
    - https://linkedin.com/in/arthrfrts
    - https://letterboxd.com/arthrfrts
    - https://www.tumblr.com/arthrfrts

relative_links:
  enabled: true
  collections: true
